# Generated by Django 4.2.10 on 2024-02-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='brand',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
