# Generated by Django 4.2.10 on 2024-02-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_remove_category_is_deleted_remove_product_is_deleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='images',
        ),
    ]
