# Generated by Django 4.2.10 on 2024-03-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0005_productimage_remove_product_images_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
